Update default_runtime.py
If set `by_epoch=False` for `log_processor`, an error is raised:
```
  File "/home/WMGDS.WMG.WARWICK.AC.UK/chen_c/project/mmengine/mmengine/runner/log_processor.py", line 314, in _check_window_size
    assert log_cfg['window_size'] != 'epoch', \
  File "/home/WMGDS.WMG.WARWICK.AC.UK/chen_c/project/mmengine/mmengine/config/config.py", line 47, in __missing__
    raise KeyError(name)
KeyError: 'window_size'
```

The reason is that here `log_processor` is checking the `window_size`, not `windows_size`: 

https://github.com/open-mmlab/mmengine/blob/50465a20022938444f90314e9ce217607d8c215c/mmengine/runner/log_processor.py#L352